### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by geeegrace02** [PanupunJanin/ku-polls#40]
1. Make small changes to the template or UI, such as making each feature larger to make it easy for users to use.
2. Add the 'change your vote' button.
3. Add duration feature which are **publish date** and **end date** to display for each poll question.

**Comment by PanupunJanin** [comment]
1. Make index page in the table form to able user to see clearer and better list
2. Change your vote button is not needed, user are able to enter the not ended question and revote them accordingly
3. There is already the publish date and end date implemented in Question model, I simply show them in the index page along with the corresponding question
